name: Publish release assets

on:
  push:
    branches:
      - main
  pull_request:

env:
  RELEASE_VERSION: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [win-x64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: "./global.json"

      - name: Restore dependencies
        run: dotnet restore --runtime ${{ matrix.arch }}

      - name: Build the application
        run: dotnet build --no-restore --runtime ${{ matrix.arch }} PxWeb/PxWeb.csproj

      - name: Publish the application
        run: dotnet publish --runtime ${{ matrix.arch }} --output ./release PxWeb/PxWeb.csproj

      - name: Create zip file
        run: zip -r release-${{ matrix.arch }}.zip ./release

      - name: Show zip size
        run: du -sh release-${{ matrix.arch }}.zip
