name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: "./global.json"

      - name: Install dotnet-coverage
        run: dotnet tool install -g dotnet-coverage

      - name: Install SonarCloud scanner
        run: dotnet tool install -g dotnet-sonarscanner
     
      - name: Coverage
        run: |
            dotnet sonarscanner begin /k:"runejo_PxWebApi"
                /o:"runejo"
                /d:sonar.token=${{ secrets.SONAR_TOKEN }}
                /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
            dotnet build --no-incremental
            dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
            dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}
